services:
  # https://documentation.portainer.io/
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer/volumes/portainer/data:/data
    restart: unless-stopped
