services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/volumes/pwfile:/mosquitto/pwfile
      - ../mosquitto/volumes/config:/mosquitto/config:ro
      - ../mosquitto/volumes/data:/mosquitto/data
      - ../mosquitto/volumes/log:/mosquitto/log
