services:
  # https://hub.docker.com/r/koenkk/zigbee2mqtt
  zigbee2mqtt:
    container_name: zigbee2mqtt
    build: ../zigbee2mqtt/.
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:8080"
    volumes:
      - ../zigbee2mqtt/volumes/data:/app/data
    devices:
      # - /dev/ttyAMA0:/dev/ttyACM0 # should work even if no adapter
      - /dev/ttyACM0:/dev/ttyACM0 # should work if CC2531 connected
      # - /dev/ttyUSB0:/dev/ttyACM0 # Electrolama zig-a-zig-ah! (zzh!) maybe other as well
    restart: unless-stopped
