services:
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Europe/Berlin
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
      - WEBPASSWORD=secret
      - INTERFACE=eth0
    volumes:
      - ./volumes/dnsmasq.d:/etc/dnsmasq.d
      - ./volumes/pihole:/etc/pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
